# Generated by Django 5.1 on 2025-08-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=10)),
                ('case_number', models.CharField(max_length=20)),
                ('filing_year', models.CharField(max_length=10)),
                ('petitioner', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent', models.CharField(blank=True, max_length=255, null=True)),
                ('next_hearing', models.CharField(blank=True, max_length=100, null=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
