# Generated by Django 5.1 on 2025-08-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casesearchlog',
            old_name='searched_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='casesearchlog',
            name='next_hearing',
        ),
        migrations.RemoveField(
            model_name='casesearchlog',
            name='petitioner',
        ),
        migrations.RemoveField(
            model_name='casesearchlog',
            name='respondent',
        ),
    ]
