# Generated by Django 5.1 on 2025-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0002_rename_searched_at_casesearchlog_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesearchlog',
            name='raw_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
